src/api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('status', views.status, name='status'),
    path('get_network', views.get_network, name='get_network'),
    path('store_filter', views.store_filter, name='store_filter'),
    path('get_bigg_models', views.get_bigg_models, name='get_bigg_models'),
    path('select_bigg_model', views.select_bigg_model, name='select_bigg_model'),
    path('get_biomodels', views.get_biomodels, name='get_biomodels'),
    path('select_biomodel', views.select_biomodel, name='select_biomodel'),
    path('get_session_data', views.get_session_data, name='get_session_data'),
    path('clear_data', views.clear_data, name='clear_data'),
    path('execute', views.execute, name='execute'),
    path('export', views.export, name='export'),
    path('serve/<str:file_name>/<path:file_type>', views.serve_file, name='serve'),
    ]

src/enalyzer/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('index.urls')),
    path('enalyzing/', include('enalyzing.urls')),
    path('api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
]

src/gemtract/urls.py
from django.urls import path

from . import views

app_name = 'gemtract'
urlpatterns = [
    path('', views.index, name='index'),
    path('filter', views.filter, name='filter'),
    path('export', views.export, name='export'),
    ]

src/gemtractor/urls.py
"""GEMtractor URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('index.urls')),
    path('gemtract/', include('gemtract.urls')),
    path('api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
]

src/index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('imprint', views.imprint, name='imprint'),
    path('learn', views.learn, name='learn'),
    ]

src/templates/base.html
{% load static %}
{# HTML5 declaration #}
<!DOCTYPE html>
<html lang="en">
	<head>
		<!--
		This page is part of the GEMtractor
		Copyright (C) 2019 Martin Scharm <https://binfalse.de>
 
		The GEMtractor is free software: you can redistribute it and/or modify
		it under the terms of the GNU General Public License as published by
		the Free Software Foundation, either version 3 of the License, or
		(at your option) any later version.

		The GEMtractor is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU General Public License for more details.
 
		You should have received a copy of the GNU General Public License
		along with this program. If not, see <http://www.gnu.org/licenses/>.
		-->

		<title>{% block title %}{% endblock %} | GEMtractor</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/w3.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'css/w3-colors-flat.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'webfonts/fonts.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'css/fontawesome-5.10.1.css' %}" type="text/css" />
		<link rel="stylesheet" href="{% static 'css/introjs.min.css' %}" type="text/css" />
		<link rel="icon" href="{% static 'pics/gemtractor-portrait.png' %}">
	</head>
	<body class="w3-flat-clouds">
		
		<div class="w3-top">
			<div class="w3-bar w3-flat-silver w3-center">
				<a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="toggleNaviMobile()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
				<a href="{% url 'index:index' %}" class="w3-bar-item w3-button w3-padding-large">
						<img src="{% static 'pics/gemtractor-landscape.png' %}" title="GEMtractor" alt="GEMtractor"/>
				</a>
				<a href="{% url 'gemtract:index' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Start</a>
				<a href="{% url 'index:learn' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Learn</a>
				<a href="{% url 'index:imprint' %}#imprint" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Imprint</a>
				<a href="{% url 'index:imprint' %}#privacy" class="w3-bar-item w3-button w3-padding-large w3-hide-small">Privacy</a>
				<a href="#" class="w3-bar-item w3-button w3-padding-large w3-hide-small helpme-btn" style="display:none" onclick="startIntro ();"><i class="fas fa-info-circle"></i></a>
			</div>
		</div>
		
		
		<div id="navMobi" class="w3-bar-block w3-flat-clouds w3-hide w3-hide-large w3-hide-medium w3-top">
			<a href="{% url 'gemtract:index' %}" class="w3-bar-item w3-button w3-padding-large" onclick="toggleNaviMobile()">Start</a>
			<a href="{% url 'index:learn' %}" class="w3-bar-item w3-button w3-padding-large" onclick="toggleNaviMobile()">Learn</a>
			<a href="{% url 'index:imprint' %}#imprint" class="w3-bar-item w3-button w3-padding-large" onclick="toggleNaviMobile()">Imprint</a>
			<a href="{% url 'index:imprint' %}#privacy" class="w3-bar-item w3-button w3-padding-large" onclick="toggleNaviMobile()">Privacy</a>
			<a href="#" class="w3-bar-item w3-button w3-padding-large helpme-btn" onclick="startIntro(true)" style="display:none"><i class="fas fa-info-circle"></i> Help me</a>
		</div>
		
		<div class="w3-content maincontent">
			<div class="w3-container w3-content w3-white w3-padding-64 w3-margin-top w3-card" id="maincard">
				{% block content %}{% endblock %}
			</div>
			{% if PREV_l %}
			<div class="prev" data-intro="You can always go back."><a href="{{PREV_l}}"><strong>{{PREV_s}}</strong><br>{{PREV_t}}</a></div>
			{% endif %}
			{% if NEXT_l %}
			<div class="next" data-intro="Here, you can go on with your analysis."><a href="{{NEXT_l}}"><strong>{{NEXT_s}}</strong><br>{{NEXT_t}}</a></div>
			{% endif %}
		</div>
		
		<footer class="w3-container w3-padding-64 w3-center w3-opacity w3-xlarge">
			<p class="w3-medium">The <a href="{% url 'index:imprint' %}#imprint">GEMtractor</a> is a project of the <a href="https://www.sbi.uni-rostock.de/">Department of Systems Biology and Bioinformatics</a> at the <a href="http://www.uni-rostock.de/">University of Rostock</a></p>
		</footer>
		<script src="{% static 'js/intro.min.js' %}"></script>
		<script>
			if ($("div[data-intro]").length) {
				$('.helpme-btn').show ();
			}
		</script>
	</body>
</html>